CREATE TABLE
    COW (
        ID INT,
        COW_OD VARCHAR(50),
        BREED VARCHAR(50),
        AGE INT,
        WEIGHT DECIMAL(10, 2),
        HEALTH_STATUS VARCHAR(50),
        PRICE DECIMAL(10, 2)
    );

CREATE TABLE
    FEEDING_MONITORING (
        ID INT,
        COW_ID INT,
        FEED_TYPE VARCHAR(50),
        QUANTITY DECIMAL(10, 2),
        FREQUENCY INT
    );

CREATE TABLE
    STAFF (ID INT, USER_ID INT, DESIGNATION VARCHAR(50));

CREATE TABLE
    VACCINE_MONITORING (
        ID INT,
        COW_ID INT,
        VACCINE_TYPE VARCHAR(50),
        DOV DATE
    );

CREATE TABLE
    USERS (
        ID INT,
        FIRST_NAME VARCHAR(50),
        LAST_NAME VARCHAR(50),
        PHONE_NUMBER VARCHAR(20),
        EMAIL VARCHAR(100),
        PASSWORD VARCHAR(100),
        ROLE VARCHAR(50)
    );